Fix LoadError with latest Julia
Since JuliaLang/julia@6e06078e1ba8ef517a89518c632ca96c3a704464 I get:
LoadError: syntax: space not allowed after ":" used for quoting

This fixes it so the package loads, but there are still a lot of
deprecation warnings.